#ifndef JS_EMBEDDED_PLATFORM_FIRMWARE_DOWNLOADER_H
#define JS_EMBEDDED_PLATFORM_FIRMWARE_DOWNLOADER_H

#include <stdint.h>

#define FIRMWARE_DOWNLOADER_SUCC 0
#define FIRMWARE_DOWNLOADER_ERR_CONN 1
#define FIRMWARE_DOWNLOADER_ERR_PROT 2
#define FIRMWARE_DOWNLOADER_ERR_WRITE 3
#define FIRMWARE_DOWNLOADER_ERR_BAD_URI 4
#define FIRMWARE_DOWNLOADER_ERR_MEM 5

uint8_t firmware_downloader_start(const char *uri);

#endif //JS_EMBEDDED_PLATFORM_FIRMWARE_DOWNLOADER_H
